# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 11:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(verbose_name=[('Canada', 'CAN'), ('Afghanistan', 'AFG'), ('Poland', 'POL'), ('France', 'FRA'), ('North Korea', 'PRK'), ('Switzerland', 'CHE'), ('Albania', 'ALB'), ('Algeria', 'DZA'), ('United States of America', 'USA'), ('United Kingdom', 'GBR'), ('Germany', 'DEU'), ('Japan', 'JPN'), ('South Korea', 'KOR'), ('Hong Kong', 'HKG')])),
                ('longitude', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-648000), django.core.validators.MaxValueValidator(-648000)])),
                ('latitude', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-324000), django.core.validators.MaxValueValidator(324000)])),
                ('surface', models.DecimalField(decimal_places=4, max_digits=904, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3)])),
                ('window_view', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name=[(0, 'shit'), (1, 'poor'), (2, 'bad'), (3, 'good'), (4, 'nice'), (5, 'great'), (6, 'awesome'), (7, 'wonderful'), (8, 'breath-taking'), (9, 'paradise')])),
            ],
        ),
    ]
