# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 11:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='country',
            field=models.TextField(choices=[('Canada', 'CAN'), ('Afghanistan', 'AFG'), ('Poland', 'POL'), ('France', 'FRA'), ('North Korea', 'PRK'), ('Switzerland', 'CHE'), ('Albania', 'ALB'), ('Algeria', 'DZA'), ('United States of America', 'USA'), ('United Kingdom', 'GBR'), ('Germany', 'DEU'), ('Japan', 'JPN'), ('South Korea', 'KOR'), ('Hong Kong', 'HKG')]),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='window_view',
            field=models.PositiveSmallIntegerField(choices=[('poor', 1), ('bad', 2), ('good', 3), ('breath-taking', 8), ('paradise', 9), ('wonderful', 7), ('awesome', 6), ('great', 5), ('shit', 0), ('nice', 4)], default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
