# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 11:53
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_propertymodel_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='surface',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=904, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
