# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 12:02
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_auto_20170104_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='surface',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=904, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
