# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 12:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_auto_20170104_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='longitude',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-648000), django.core.validators.MaxValueValidator(648000)]),
        ),
    ]
