# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 12:31
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('estate', '0008_auto_20170104_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2017, 1, 4, 12, 31, 52, 555476, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2017, 1, 4, 12, 31, 52, 555546, tzinfo=utc), validators=[django.core.validators.MinValueValidator(models.DateTimeField(default=datetime.datetime(2017, 1, 4, 12, 31, 52, 555476, tzinfo=utc)))])),
                ('start_price', models.DecimalField(decimal_places=2, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=902, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))])),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, default=models.DecimalField(decimal_places=2, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=902, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))]), max_digits=902, validators=[django.core.validators.MinValueValidator(models.DecimalField(decimal_places=2, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=902, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))]))])),
                ('owner_key', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='biddingmodel_owner_user', to='users.UserProfile')),
                ('property_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estate.PropertyModel')),
                ('winner_key', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='biddingmodel_winner_user', to='users.UserProfile')),
            ],
        ),
    ]
